const {chromium}=require(process.env.PLAYWRIGHT_PATH||'/private/tmp/sharpdots-crm-tools/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
  const b=await chromium.launch();
  const page=await b.newPage({viewport:{width:1440,height:1000}});
  const errors=[],api=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))api.push(r.url());});
  await page.goto('http://127.0.0.1:4187/index.html?crm=1');
  await page.waitForSelector('.crm-deal');
  assert.equal(await page.locator('.crm-deal').count(),12);
  await page.locator('.crm-deal').filter({hasText:'Customer reactivation'}).click();
  await page.locator('[data-tab="documents"]').click();
  await page.locator('[data-status="completed"]').click();
  await page.locator('[data-action="win"]').click();
  await page.locator('[data-action="confirm-win"]').click();
  await page.locator('[data-tab="handoff"]').click();
  const form=page.locator('form[data-handoff-form="production"]');
  await form.locator('[name=owner]').selectOption('Warren Corrales');
  await form.locator('[name=target]').fill('2026-10-15');
  await form.locator('[name=assets]').check();
  await form.locator('[type=submit]').click();
  await page.locator('[data-action=queue-handoff][data-lane=production]').click();
  await page.locator('[data-action=accept-handoff][data-lane=production]').click();
  await page.locator('#crmBillingForm [name=start]').fill('2026-10-10');
  await page.locator('#crmBillingForm [type=submit]').click();
  await page.locator('[data-action=billing-ready]').click();
  await page.screenshot({path:'/private/tmp/crm-handoff.png'});
  await page.locator('[data-tab=records]').click();
  await page.locator('[data-action=record-open]').first().click();
  assert.equal(await page.locator('#crmOpportunity').inputValue(),await page.evaluate(()=>JSON.parse(localStorage.getItem('sharpdots-crm-draft-v1')).opportunities[8].id));
  await page.locator('[data-action=nav][data-page=quote]').click();
  await page.locator('#crmOpportunity').selectOption({label:'O-000004 · Fall product catalog'});
  assert.equal(await page.evaluate(()=>printQuote.customerCompany),'Cedar & Co.');
  await page.locator('#printQuoteView [data-record-action=version]').click();
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('sharpdots-crm-draft-v1')).opportunities[3].records[0].version),2);
  await page.locator('#printQuoteView [data-record-action=detach]').click();
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('sharpdots-crm-draft-v1')).opportunities[3].records.length),0);
  await page.locator('#printQuoteView [data-record-action=attach]').click();
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('sharpdots-crm-draft-v1')).opportunities[3].records.length),1);
  await page.locator('#crmOpportunity').selectOption('');
  assert.equal(await page.locator('#printQuoteView [data-record-action=attach]').isDisabled(),true);
  await page.locator('[data-action=nav][data-page=pipeline]').click();
  await page.locator('[data-action=new]').first().click();
  await page.locator('#crmEditForm [name=title]').fill('QA draft opportunity');
  await page.locator('#crmEditForm [name=account]').fill('QA account');
  await page.locator('#crmEditForm [name=contact]').fill('QA buyer');
  await page.locator('#crmEditForm [type=submit]').click();
  await page.locator('[data-action=lost]').click();
  await page.locator('#crmLostForm [type=submit]').click();
  await page.locator('[data-action=close-detail]').click();
  await page.reload();
  await page.waitForSelector('.crm-deal');
  assert.equal(await page.locator('.crm-deal').count(),13);
  const data=await page.evaluate(()=>JSON.parse(localStorage.getItem('sharpdots-crm-draft-v1')));
  assert.equal(data.opportunities[8].status,'won');
  assert.equal(data.opportunities[8].handoffs.production.status,'accepted');
  assert.equal(data.opportunities[8].billing.status,'ready');
  await page.locator('#crmSearch').fill('QA draft');
  await page.locator('#crmScope').selectOption('lost');
  assert.equal(await page.locator('.crm-deal').count(),1);
  await page.locator('#crmSearch').fill('');
  await page.locator('#crmScope').selectOption('all');
  for(const [width,height]of [[1440,1000],[1188,915],[2560,1080],[390,844]]){
    await page.setViewportSize({width,height});
    await page.screenshot({path:`/private/tmp/crm-${width}.png`});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'page overflow '+width);
  }
  assert.deepEqual(errors,[]);
  assert.deepEqual(api,[],'API requests must remain local in preview');
  console.log('PASS: navigation, linked records, sample sign/close, production handoff, billing readiness, intake, persistence, search, 4 viewport bounds, no API requests.');
  await b.close();
})().catch(e=>{console.error(e);process.exit(1);});
